"""traduzindo_banco_para_ptbr

Revision ID: 2fe595560f77
Revises: 73874ef7296d
Create Date: 2026-04-09 19:35:22.616165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fe595560f77'
down_revision: Union[str, Sequence[str], None] = '73874ef7296d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_pro_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_pro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_perfil'), 'usuarios', ['perfil'], unique=False)
    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('autor_usuario_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('foco_corporal', sa.String(length=30), nullable=False),
    sa.Column('tipo_analise', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercicio_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('paciente_usuario_id', sa.String(), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], ),
    sa.ForeignKeyConstraint(['paciente_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_usuario_id', sa.String(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['exercicio_configs.id'], ),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], ),
    sa.ForeignKeyConstraint(['paciente_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('paciente_usuario_id', sa.String(), nullable=False),
    sa.Column('exercicio_id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], ),
    sa.ForeignKeyConstraint(['paciente_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumos_sessao',
    sa.Column('sessao_id', sa.String(), nullable=False),
    sa.Column('repeticoes', sa.Integer(), nullable=False),
    sa.Column('adm', sa.Float(), nullable=False),
    sa.Column('cadencia', sa.Float(), nullable=True),
    sa.Column('alertas', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ),
    sa.PrimaryKeyConstraint('sessao_id')
    )
    op.drop_table('session_summaries')
    op.drop_table('sessions')
    op.drop_table('assignments')
    op.drop_table('exercise_configs')
    op.drop_table('exercises')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_pro_owner_id', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pro_owner_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pro_owner_id'], ['users.id'], name='fk_users_pro_owner_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_pro_owner_id', 'users', ['pro_owner_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assignments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['exercise_configs.id'], name='assignments_config_id_fkey'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='assignments_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name='assignments_patient_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assignments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('config_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='sessions_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='sessions_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name='sessions_patient_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('session_summaries',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rom', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cadence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('alerts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='session_summaries_session_id_fkey'),
    sa.PrimaryKeyConstraint('session_id', name='session_summaries_pkey')
    )
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exercises_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('body_focus', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('analysis_kind', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='exercises_created_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exercises_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('exercise_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='exercise_configs_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name='exercise_configs_patient_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exercise_configs_pkey')
    )
    op.drop_table('resumos_sessao')
    op.drop_table('sessoes')
    op.drop_table('prescricoes')
    op.drop_table('exercicio_configs')
    op.drop_table('exercicios')
    op.drop_index(op.f('ix_usuarios_perfil'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
